/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalecorePortalRouteImport } from './routes/$locale/(core)/portal'
import { Route as LocaleauthSignInIndexRouteImport } from './routes/$locale/(auth)/sign-in/index'
import { Route as LocalecorePortalMachinesIndexRouteImport } from './routes/$locale/(core)/portal/machines/index'
import { Route as LocalecorePortalDashboardIndexRouteImport } from './routes/$locale/(core)/portal/dashboard/index'

const LocalecorePortalRoute = LocalecorePortalRouteImport.update({
  id: '/$locale/(core)/portal',
  path: '/$locale/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthSignInIndexRoute = LocaleauthSignInIndexRouteImport.update({
  id: '/$locale/(auth)/sign-in/',
  path: '/$locale/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalecorePortalMachinesIndexRoute =
  LocalecorePortalMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => LocalecorePortalRoute,
  } as any)
const LocalecorePortalDashboardIndexRoute =
  LocalecorePortalDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => LocalecorePortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale/portal': typeof LocalecorePortalRouteWithChildren
  '/$locale/sign-in': typeof LocaleauthSignInIndexRoute
  '/$locale/portal/dashboard': typeof LocalecorePortalDashboardIndexRoute
  '/$locale/portal/machines': typeof LocalecorePortalMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/$locale/portal': typeof LocalecorePortalRouteWithChildren
  '/$locale/sign-in': typeof LocaleauthSignInIndexRoute
  '/$locale/portal/dashboard': typeof LocalecorePortalDashboardIndexRoute
  '/$locale/portal/machines': typeof LocalecorePortalMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale/(core)/portal': typeof LocalecorePortalRouteWithChildren
  '/$locale/(auth)/sign-in/': typeof LocaleauthSignInIndexRoute
  '/$locale/(core)/portal/dashboard/': typeof LocalecorePortalDashboardIndexRoute
  '/$locale/(core)/portal/machines/': typeof LocalecorePortalMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale/portal'
    | '/$locale/sign-in'
    | '/$locale/portal/dashboard'
    | '/$locale/portal/machines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/portal'
    | '/$locale/sign-in'
    | '/$locale/portal/dashboard'
    | '/$locale/portal/machines'
  id:
    | '__root__'
    | '/$locale/(core)/portal'
    | '/$locale/(auth)/sign-in/'
    | '/$locale/(core)/portal/dashboard/'
    | '/$locale/(core)/portal/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocalecorePortalRoute: typeof LocalecorePortalRouteWithChildren
  LocaleauthSignInIndexRoute: typeof LocaleauthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale/(core)/portal': {
      id: '/$locale/(core)/portal'
      path: '/$locale/portal'
      fullPath: '/$locale/portal'
      preLoaderRoute: typeof LocalecorePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/sign-in/': {
      id: '/$locale/(auth)/sign-in/'
      path: '/$locale/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleauthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(core)/portal/machines/': {
      id: '/$locale/(core)/portal/machines/'
      path: '/machines'
      fullPath: '/$locale/portal/machines'
      preLoaderRoute: typeof LocalecorePortalMachinesIndexRouteImport
      parentRoute: typeof LocalecorePortalRoute
    }
    '/$locale/(core)/portal/dashboard/': {
      id: '/$locale/(core)/portal/dashboard/'
      path: '/dashboard'
      fullPath: '/$locale/portal/dashboard'
      preLoaderRoute: typeof LocalecorePortalDashboardIndexRouteImport
      parentRoute: typeof LocalecorePortalRoute
    }
  }
}

interface LocalecorePortalRouteChildren {
  LocalecorePortalDashboardIndexRoute: typeof LocalecorePortalDashboardIndexRoute
  LocalecorePortalMachinesIndexRoute: typeof LocalecorePortalMachinesIndexRoute
}

const LocalecorePortalRouteChildren: LocalecorePortalRouteChildren = {
  LocalecorePortalDashboardIndexRoute: LocalecorePortalDashboardIndexRoute,
  LocalecorePortalMachinesIndexRoute: LocalecorePortalMachinesIndexRoute,
}

const LocalecorePortalRouteWithChildren =
  LocalecorePortalRoute._addFileChildren(LocalecorePortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocalecorePortalRoute: LocalecorePortalRouteWithChildren,
  LocaleauthSignInIndexRoute: LocaleauthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
